#!/usr/bin/env python3
"""Embeds mbr.bin/stage2.bin/kernel.flat.bin as C byte arrays so the
installer binary (installer/src/installer_main.c) can write the exact same
boot chain that bootdisk.img's Makefile target writes at build time --
except the installer writes it at INSTALL time, to whatever disk it finds,
using only what's inside its own binary (its boot media has no host
filesystem to read these files from once it's running).

Usage: gen_installer_assets.py <mbr.bin> <stage2.bin> <kernel.flat.bin> <out.h>
"""
import sys


def emit_array(f, name, data):
    f.write(f"static const unsigned char {name}[] = {{\n")
    for i in range(0, len(data), 16):
        chunk = data[i:i + 16]
        f.write("    " + ",".join(f"0x{b:02X}" for b in chunk) + ",\n")
    if len(data) == 0:
        f.write("    0\n")  # a zero-length array isn't valid C
    f.write("};\n")
    f.write(f"static const unsigned int {name}_len = {len(data)}u;\n\n")


def main():
    if len(sys.argv) != 5:
        print(__doc__)
        sys.exit(1)

    mbr_path, stage2_path, kernel_path, out_path = sys.argv[1:5]

    with open(mbr_path, "rb") as f:
        mbr = f.read()
    with open(stage2_path, "rb") as f:
        stage2 = f.read()
    with open(kernel_path, "rb") as f:
        kernel = f.read()

    assert len(mbr) == 512, f"mbr.bin must be exactly 512 bytes, got {len(mbr)}"

    with open(out_path, "w") as f:
        f.write("#ifndef INSTALLER_ASSETS_H\n#define INSTALLER_ASSETS_H\n\n")
        f.write("/* Generated by installer/tools/gen_installer_assets.py -- do not edit by hand. */\n\n")
        emit_array(f, "installer_mbr_bin", mbr)
        emit_array(f, "installer_stage2_bin", stage2)
        emit_array(f, "installer_kernel_bin", kernel)
        f.write("#endif\n")

    print(f"Wrote {out_path}: mbr={len(mbr)}B stage2={len(stage2)}B kernel={len(kernel)}B")


if __name__ == "__main__":
    main()
